### ISSUE TITLE
Migrate to kubevirt organization

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt-template-validator#37]
The repository should be migrated under the umbrella of KubeVirt organization to have the same flow as for every project linked.

/cc @fabiand @ksimon1

**Comment by fabiand** [comment]
Sounds reasonable.

Please make me an admin and I can initiate the transfer.

**Comment by fromanirh** [comment]
> Sounds reasonable. Please make me an admin and I can initiate the transfer.

Request sent.

**Comment by fabiand** [comment]
Done!
